/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p obex_server_session.h:obex_server_session.cpp -i types.h ../xml/obex_server_session.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "obex_server_session.h"

/*
 * Implementation of interface class OrgOpenobexServerSessionInterface
 */

OrgOpenobexServerSessionInterface::OrgOpenobexServerSessionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgOpenobexServerSessionInterface::~OrgOpenobexServerSessionInterface()
{
}

