/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p serial_proxy_manager.h:serial_proxy_manager.cpp -i types.h ../xml/serial_proxy_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SERIAL_PROXY_MANAGER_H_1312840544
#define SERIAL_PROXY_MANAGER_H_1312840544

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "types.h"

/*
 * Proxy class for interface org.bluez.SerialProxyManager
 */
class OrgBluezSerialProxyManagerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.bluez.SerialProxyManager"; }

public:
    OrgBluezSerialProxyManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgBluezSerialProxyManagerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> CreateProxy(const QString &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("CreateProxy"), argumentList);
    }

    inline QDBusPendingReply<QStringList> ListProxies()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ListProxies"), argumentList);
    }

    inline QDBusPendingReply<> RemoveProxy(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("RemoveProxy"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void ProxyCreated(const QString &in0);
    void ProxyRemoved(const QString &in0);
};

namespace org {
  namespace bluez {
    typedef ::OrgBluezSerialProxyManagerInterface SerialProxyManager;
  }
}
#endif
